export enum Role {
  USER = 'user',
  MODEL = 'model'
}

export interface Attachment {
  mimeType: string;
  data: string; // Base64 string
}

export interface Message {
  id: string;
  role: Role;
  content: string;
  timestamp: number;
  isError?: boolean;
  attachments?: Attachment[]; // Files sent by user
  generatedImage?: string;    // Image generated by AI (Base64)
}

export enum AppMode {
  CHAT = 'chat',
  CODING = 'coding',
  MATH = 'math',
  IMAGE_GEN = 'image_gen'
}

export interface ChatState {
  messages: Message[];
  isLoading: boolean;
}