import express from 'express';
import cors from 'cors';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, resolve, join } from 'path';
import fs from 'fs';

// Resolve paths for ES Modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load .env from the root directory
dotenv.config({ path: resolve(__dirname, '../.env') });

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(cors());
app.use(express.json({ limit: '50mb' }));

// --- CONFIGURATION ---
// Using gemini-2.5-flash as default for text
const TEXT_MODEL = 'gemini-2.5-flash';
const IMAGE_MODEL = 'imagen-4.0-generate-001';

// --- SERVE STATIC FILES (PRODUCTION) ---
const distPath = resolve(__dirname, '../dist');
const indexPath = join(distPath, 'index.html');

console.log(`Server starting...`);
console.log(`Current directory: ${process.cwd()}`);
console.log(`Looking for static files in: ${distPath}`);

if (fs.existsSync(distPath)) {
  console.log('Static files found. Serving React app.');
  app.use(express.static(distPath));
} else {
  console.warn('WARNING: dist folder not found. Make sure "npm run build" ran successfully.');
}

// Health Check
app.get('/health', (req, res) => {
  res.status(200).send('BACH AI Backend (Node.js) is Running');
});

// Chat Endpoint (Streaming)
app.post('/api/chat', async (req, res) => {
  if (!process.env.API_KEY) {
    console.error("API_KEY is missing in environment variables.");
    return res.status(500).json({ error: "Server Error: Configuration missing (API Key)." });
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const { message, attachments, history, systemInstruction } = req.body;

    // Set headers for SSE
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');

    // Format History for SDK
    // Logic: Convert raw frontend messages to Gemini "Content" objects
    const validHistory = Array.isArray(history) ? history.map(msg => {
      const parts = [];
      
      // Handle Attachments
      if (msg.attachments && Array.isArray(msg.attachments)) {
        msg.attachments.forEach(att => {
          if (att.mimeType && att.data) {
            parts.push({ inlineData: { mimeType: att.mimeType, data: att.data } });
          }
        });
      }
      
      // Handle Generated Images in history (as a placeholder text or description)
      if (msg.generatedImage) {
        parts.push({ text: "[Image Generated by AI]" });
      }
      
      // Handle Text Content
      if (msg.content && typeof msg.content === 'string' && msg.content.trim() !== "") {
        parts.push({ text: msg.content });
      } 
      
      // Safety fallback: Gemini throws error if parts is empty
      if (parts.length === 0) {
        parts.push({ text: "." }); 
      }
      
      return {
        role: msg.role === 'user' ? 'user' : 'model',
        parts: parts
      };
    }) : [];

    const chat = ai.chats.create({
      model: TEXT_MODEL,
      history: validHistory,
      config: { systemInstruction },
    });

    // Prepare Current Message
    const currentParts = [];
    if (attachments && Array.isArray(attachments)) {
      attachments.forEach(att => {
         if (att.mimeType && att.data) {
           currentParts.push({
             inlineData: { mimeType: att.mimeType, data: att.data }
           });
         }
      });
    }
    if (message) currentParts.push({ text: message });

    // Fallback if empty message sent
    if (currentParts.length === 0) {
       currentParts.push({ text: "." });
    }

    const result = await chat.sendMessageStream({ message: currentParts });

    for await (const chunk of result) {
      if (chunk.text) {
        res.write(`data: ${JSON.stringify({ text: chunk.text })}\n\n`);
      }
    }

    res.write('data: [DONE]\n\n');
    res.end();

  } catch (error) {
    console.error('Chat API Error Full Details:', error);
    
    // Create a user-friendly error message
    let errorMessage = "Internal Server Error";
    if (error.message) errorMessage = error.message;
    if (error.toString().includes("404")) errorMessage = "Model not found or API Key invalid for this model.";
    
    const errorResponse = JSON.stringify({ error: errorMessage });
    
    if (!res.headersSent) {
        res.status(500).write(`data: ${errorResponse}\n\n`);
    } else {
        res.write(`data: ${errorResponse}\n\n`);
    }
    res.end();
  }
});

// Image Generation Endpoint
app.post('/api/generate-image', async (req, res) => {
  if (!process.env.API_KEY) {
    return res.status(500).json({ error: "Missing API Key." });
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const { prompt } = req.body;
    
    console.log(`Generating image for prompt: ${prompt}`);

    const response = await ai.models.generateImages({
      model: IMAGE_MODEL,
      prompt: prompt,
      config: { numberOfImages: 1, outputMimeType: 'image/jpeg' },
    });

    if (response.generatedImages?.length > 0) {
      res.json({ imageBytes: response.generatedImages[0].image.imageBytes });
    } else {
      throw new Error('No image generated from API.');
    }
  } catch (error) {
    console.error("Image Gen Error:", error);
    res.status(500).json({ error: error.message || "Failed to generate image" });
  }
});

// Fallback for SPA Routing
app.get('*', (req, res) => {
    if (fs.existsSync(indexPath)) {
        res.sendFile(indexPath);
    } else {
        res.status(404).send('Backend running. Build frontend to view UI.');
    }
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`🚀 Node.js Backend running on port ${PORT}`);
});